version: 0.1

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo pre-build...
  build:
    commands:
      - echo Build started
      - npm install
  post_build:
    commands:
      - echo Build completed