version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
    - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    artifact1:
      base-directory: .
      files:
        - 'lib/client/*' 
#    artifact2:
#      base-directory: lib/server
#      files:
#        - '**/*'       
