version: "3.9"
services:

  back:
#    build:
#      dockerfile: Dockerfile
#      context: .
#      target: backend
    image: al7z/nodechess:back
    depends_on:
    - database
    ports:
    - 8081:8081

  database:
    image: mongo
    ports:
    - 27017:27017

  front:
#    build:
#      dockerfile: Dockerfile
#      context: .
#      target: frontend
    image: al7z/nodechess:front
    ports:
    - "8080:8080"
    depends_on:
    - back
